apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://172.30.40.68:6443
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: b364f698
      source:
        repoURL: https://github.com/jzhupup/applicationset.git
        targetRevision: HEAD
        path: examples/git-generator-files-discovery/apps/guestbook
      destination:
        server: '{{.url}}'
        #server: '{{cluster.address}}'
        namespace: jzh-demo
