apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: zcl-97
        url: https://172.16.222.97:6443
      - cluster: zcl-98
        url: https://172.16.222.98:6443
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: b364f698
      source:
        repoURL: https://github.com/jzhupup/applicationset.git
        targetRevision: HEAD
        path: examples/git-generator-files-discovery/apps/guestbook
      destination:
        server: '{{.url}}'
        namespace: default
