apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-appset
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://172.16.222.97:6443
      - cluster: engineering-prod
        url: https://172.16.222.98:6443
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: b364f698
      source:
        repoURL: https://github.com/jzhupup/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: default
